## Get ip without network packages >> awk '/32 host/ { print i } {i=$2}' /proc/net/fib_trie
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait an specific amount of seconds
      ansible.builtin.wait_for:
        timeout: "{{ time }}"
